package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CSS_Declaration = 0;
  public static final int CSS_Declaration_Block = 1;
  public static final int CSS_File = 2;
  public static final int CSS_Ruleset = 3;
  public static final int CSS_Selector = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL);
    builder.put(0x5ecb502d234d3d23L, CSS_Declaration);
    builder.put(0x5ecb502d234d3d29L, CSS_Declaration_Block);
    builder.put(0x5ecb502d234d3d35L, CSS_File);
    builder.put(0x5ecb502d234d3d2fL, CSS_Ruleset);
    builder.put(0x5ecb502d234d3d2cL, CSS_Selector);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
