package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCSS_Declaration = createDescriptorForCSS_Declaration();
  /*package*/ final ConceptDescriptor myConceptCSS_Declaration_Block = createDescriptorForCSS_Declaration_Block();
  /*package*/ final ConceptDescriptor myConceptCSS_File = createDescriptorForCSS_File();
  /*package*/ final ConceptDescriptor myConceptCSS_Ruleset = createDescriptorForCSS_Ruleset();
  /*package*/ final ConceptDescriptor myConceptCSS_Selector = createDescriptorForCSS_Selector();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCSS_Declaration, myConceptCSS_Declaration_Block, myConceptCSS_File, myConceptCSS_Ruleset, myConceptCSS_Selector);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CSS_Declaration:
        return myConceptCSS_Declaration;
      case LanguageConceptSwitch.CSS_Declaration_Block:
        return myConceptCSS_Declaration_Block;
      case LanguageConceptSwitch.CSS_File:
        return myConceptCSS_File;
      case LanguageConceptSwitch.CSS_Ruleset:
        return myConceptCSS_Ruleset;
      case LanguageConceptSwitch.CSS_Selector:
        return myConceptCSS_Selector;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCSS_Declaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Declaration", 0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d23L);
    b.class_(false, false, false);
    b.origin("r:237636ed-9075-44e0-b93d-2072f5acf6fe(CSS.structure)/6830641414633504035");
    b.version(2);
    b.property("property", 0x5ecb502d234d3d24L).type(PrimitiveTypeId.STRING).origin("6830641414633504036").done();
    b.property("value", 0x5ecb502d234d3d26L).type(PrimitiveTypeId.STRING).origin("6830641414633504038").done();
    b.alias("declaration");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Declaration_Block() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Declaration_Block", 0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d29L);
    b.class_(false, false, false);
    b.origin("r:237636ed-9075-44e0-b93d-2072f5acf6fe(CSS.structure)/6830641414633504041");
    b.version(2);
    b.aggregate("declarations", 0x5ecb502d234d3d2aL).target(0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d23L).optional(true).ordered(true).multiple(true).origin("6830641414633504042").done();
    b.alias("declaratio block");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_File() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_File", 0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d35L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:237636ed-9075-44e0-b93d-2072f5acf6fe(CSS.structure)/6830641414633504053");
    b.version(2);
    b.aggregate("rulesets", 0x5ecb502d234d3d38L).target(0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d2fL).optional(true).ordered(true).multiple(true).origin("6830641414633504056").done();
    b.alias("css file");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Ruleset() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Ruleset", 0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d2fL);
    b.class_(false, false, false);
    b.origin("r:237636ed-9075-44e0-b93d-2072f5acf6fe(CSS.structure)/6830641414633504047");
    b.version(2);
    b.aggregate("selectors", 0x5ecb502d234d3d30L).target(0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d2cL).optional(false).ordered(true).multiple(true).origin("6830641414633504048").done();
    b.aggregate("block", 0x5ecb502d234d3d32L).target(0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d29L).optional(false).ordered(true).multiple(false).origin("6830641414633504050").done();
    b.alias("ruleset");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Selector() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Selector", 0x44cfae9e54c64718L, 0x8d0e41cb3fa3131eL, 0x5ecb502d234d3d2cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:237636ed-9075-44e0-b93d-2072f5acf6fe(CSS.structure)/6830641414633504044");
    b.version(2);
    b.alias("selector");
    return b.create();
  }
}
